### ISSUE TITLE
Error parser

### ISSUE THREAD

**Issue by DarkoMir** [broadlink-ac/broadlink_ac_mqtt_docker#6]
Hi, I have this error since this year

[dario@hassio broadlink_ac_mqtt]$ ./monitor.py 
Traceback (most recent call last):
  File "/home/dario/broadlink_ac_mqtt/./monitor.py", line 9, in <module>
    import broadlink_ac_mqtt.AcToMqtt as AcToMqtt
  File "/home/dario/broadlink_ac_mqtt/broadlink_ac_mqtt/AcToMqtt.py", line 14, in <module>
    import broadlink_ac_mqtt.classes.broadlink.ac_db as broadlink
  File "/home/dario/broadlink_ac_mqtt/broadlink_ac_mqtt/classes/broadlink/ac_db.py", line 10, in <module>
    import parser
ModuleNotFoundError: No module named 'parser'

Until december all was working really good.
I am on Manjaro, all updated.
Python 3.10.2

Am I missing a python module, probably from an upgrade?

**Comment by DarkoMir** [comment]
And it's a python version problem.
I need python2 that it's gone without trace

**Comment by woann** [comment]
Me too! ,How to end the problem

**Comment by liaan** [comment]
Sounds like module requirement.  Thinks its the arguement parser..    I don't look after the docker version.. did you guys try running normal version outside docker?

**Comment by DarkoMir** [comment]
> Me too! ,How to end the problem

Installed python 2 stuff and all it's ok. 


> Sounds like module requirement. Thinks its the arguement parser.. I don't look after the docker version.. did you guys try running normal version outside docker?

for me, yes. No docker
